### ISSUE TITLE
CI: Azure runners are not picking up CI jobs

### ISSUE THREAD

**Issue by CarlosNihelton** [ubuntu/GoWSL#113]
The last three attempts to run the QA on Azure CI workflow stays put waiting on self-hosted runners to pick up the job, but they never did. That requires investigation and fix. It's likely an issue on the self-hosted runner.

**Comment by CarlosNihelton** [comment]
Failed to create a session. The runner registration has been deleted from the server, please re-configure. Runner registrations are automatically deleted for runners that have not connected to the service recently.
"Runner listener exit with terminated error, stop the service, no retry needed."
"Exiting runner..."

**Comment by EduardGomezEscandell** [comment]
https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/removing-self-hosted-runners#removing-a-runner-from-a-repository

> A self-hosted runner is automatically removed from GitHub if it has not connected to GitHub Actions for more than 14 days. An ephemeral self-hosted runner is automatically removed from GitHub if it has not connected to GitHub Actions for more than 1 day.

I used to fix every now and then in this repo :sweat_smile:. You may want to set up a cron job to hello-world once a week.

**Comment by CarlosNihelton** [comment]
Yeah. The runner was automatically removed because it remained out of touch for more than the allowed period (14 days by default).
After removing the `.runner` file and reconfiguring the connection to GH manually on the runner, everything went back to normal.
